openapi: 3.0.0
info:
  title: WB Supplier Stats
  version: "1.0"
servers:
- url: https://suppliers-stats.wildberries.ru/api/v1/supplier
security:
- Key: []
paths:
  /orders:
    get:
      description: ""
      operationId: get-orders
      parameters:
      - description: "1 - то за одну дату, 0 - за все что больше переданной даты"
        explode: true
        in: query
        name: flag
        required: false
        schema:
          format: int32
          type: integer
        style: form
      - explode: true
        in: query
        name: dateFrom
        required: true
        schema:
          example: 2021-01-06T21:00:00Z
          format: date-time
          type: string
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/get_orders_200_response_inner'
                type: array
          description: OK
      summary: Get Orders
      tags:
      - stats
  /incomes:
    get:
      description: ""
      operationId: get-incomes
      parameters:
      - description: Дата и время от которых выгружается информация
        explode: true
        in: query
        name: dateFrom
        required: true
        schema:
          example: 2021-01-06T21:00:00Z
          format: date-time
          type: string
        style: form
      responses:
        "200":
          content:
            application/json:
              examples: {}
              schema:
                items:
                  $ref: '#/components/schemas/get_incomes_200_response_inner'
                type: array
          description: OK
      summary: Get Incomes
      tags:
      - stats
  /stocks:
    get:
      description: ""
      operationId: get-stocks
      parameters:
      - description: Дата и время от которых выгружается информация
        explode: true
        in: query
        name: dateFrom
        required: true
        schema:
          example: 2021-01-06T21:00:00Z
          format: date-time
          type: string
        style: form
      responses:
        "200":
          content:
            application/json:
              examples: {}
              schema:
                items:
                  $ref: '#/components/schemas/get_stocks_200_response_inner'
                type: array
          description: OK
      summary: Get Stocks
      tags:
      - stats
  /sales:
    get:
      description: ""
      operationId: get-sales
      parameters:
      - description: Дата и время от которых выгружается информация
        explode: true
        in: query
        name: dateFrom
        required: true
        schema:
          example: 2021-01-06T21:00:00Z
          format: date-time
          type: string
        style: form
      - description: "1 - то за одну дату, 0 - за все что больше переданной даты"
        explode: true
        in: query
        name: flag
        required: false
        schema:
          format: int32
          type: integer
        style: form
      responses:
        "200":
          content:
            application/json:
              examples: {}
              schema:
                items:
                  $ref: '#/components/schemas/get_sales_200_response_inner'
                type: array
          description: OK
      summary: Get Sales
      tags:
      - stats
  /stochrancost:
    get:
      description: Получить информацию о платном хранилище - факт
      operationId: get-paid-storage
      parameters:
      - description: Дата и время от которых выгружается информация
        explode: true
        in: query
        name: dateFrom
        required: true
        schema:
          example: 2021-01-06T21:00:00Z
          format: date-time
          type: string
        style: form
      - description: Дата и время до которых выгружается информация
        explode: true
        in: query
        name: dateTo
        required: true
        schema:
          example: 2021-01-06T21:00:00Z
          format: date-time
          type: string
        style: form
      responses:
        "200":
          content:
            application/json:
              examples: {}
              schema:
                items:
                  $ref: '#/components/schemas/get_paid_storage_200_response_inner'
                type: array
          description: OK
      summary: Get Paid Storage
      tags:
      - stats
  /reportDetailByPeriod:
    get:
      description: Получить информацию об отчёте о продажах по реализации
      operationId: get-report-detail-by-period
      parameters:
      - description: Начальная дата периода
        explode: true
        in: query
        name: dateFrom
        required: true
        schema:
          example: 2021-01-06T21:00:00Z
          format: date-time
          type: string
        style: form
      - description: Конечная дата периода
        explode: true
        in: query
        name: dateTo
        required: true
        schema:
          example: 2021-01-06T21:00:00Z
          format: date-time
          type: string
        style: form
      - description: "Максимальное количество записей, получаемых при запросе"
        explode: true
        in: query
        name: limit
        required: true
        schema:
          format: int64
          minimum: 0
          type: integer
        style: form
      - description: "Идентификатор записи, начиная с которой нужно получать данны\
          е при запросе"
        explode: true
        in: query
        name: rrdid
        required: true
        schema:
          format: int64
          minimum: 0
          type: integer
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/get_report_detail_by_period_200_response_inner'
                minItems: 1
                type: array
                uniqueItems: true
                x-examples:
                  example-1:
                  - realizationreport_id: 5672617
                    rrd_id: 4938703342
                    gi_id: 5247027
                    subject_name: Куртки
                    nm_id: 47548690
                    brand_name: Fenix Wear
                    sa_name: H328темно-синий
                    ts_name: "48"
                    barcode: "2013339065006"
                    doc_type_name: Продажа
                    quantity: 0
                    retail_price: 0
                    retail_amount: 0
                    sale_percent: 0
                    commission_percent: 0
                    office_name: Электросталь
                    supplier_oper_name: Логистика
                    order_dt: 2021-12-03T00:00:00Z
                    sale_dt: 2021-12-03T00:00:00Z
                    rr_dt: 2021-12-03T00:00:00Z
                    shk_id: 4471876369
                    retail_price_withdisc_rub: 0
                    delivery_amount: 0
                    return_amount: 1
                    delivery_rub: 33
                    gi_box_type_name: Микс
                    product_discount_for_report: 0
                    supplier_promo: 0
                    rid: 150108717021
                    ppvz_spp_prc: 0
                    ppvz_kvw_prc_base: 0
                    ppvz_kvw_prc: 0
                    ppvz_sales_commission: 0
                    ppvz_for_pay: 0
                    ppvz_reward: 0
                    ppvz_vw: 0
                    ppvz_vw_nds: 0
                    ppvz_office_id: 0
                    ppvz_office_name: Пункт самовывоза (ПВЗ)
                    ppvz_supplier_id: 0
          description: OK
      summary: Get Report Detail By Period
      tags:
      - stats
components:
  schemas:
    get_orders_200_response_inner:
      example:
        date: date
        supplierArticle: supplierArticle
        discountPercent: 1.4658129805029452
        incomeID: 5
        odid: 5
        isCancel: true
        totalPrice: 6.027456183070403
        subject: subject
        lastChangeDate: lastChangeDate
        oblast: oblast
        nmId: 2
        warehouseName: warehouseName
        gNumber: gNumber
        srid: srid
        number: 0
        cancel_dt: cancel_dt
        techSize: techSize
        category: category
        barcode: barcode
        brand: brand
      properties:
        number:
          description: номер заказа
          format: int64
          type: integer
        date:
          description: дата заказа
          type: string
        lastChangeDate:
          description: дата время обновления информации в сервисе
          type: string
        supplierArticle:
          description: ваш артикул
          type: string
        techSize:
          description: размер
          type: string
        barcode:
          description: штрих-код
          type: string
        totalPrice:
          description: цена до согласованной скидки/промо/спп
          type: number
        discountPercent:
          description: согласованный итоговый дисконт
          type: number
        warehouseName:
          description: склад отгрузки
          type: string
        oblast:
          description: область
          type: string
        incomeID:
          description: номер поставки
          format: int64
          type: integer
        odid:
          description: уникальный идентификатор позиции заказа
          format: int64
          type: integer
        nmId:
          description: Код WB
          type: integer
        subject:
          description: предмет
          type: string
        category:
          description: категория
          type: string
        brand:
          description: бренд
          type: string
        isCancel:
          description: "признак отмены заказа (0 – отмены не было, 1 – отмена была"
          type: boolean
        cancel_dt:
          description: дата отмены заказа
          type: string
        gNumber:
          description: Номер заказа
          type: string
        srid:
          description: Srid
          type: string
      required:
      - barcode
      - brand
      - cancel_dt
      - category
      - date
      - discountPercent
      - gNumber
      - incomeID
      - isCancel
      - lastChangeDate
      - nmId
      - number
      - oblast
      - odid
      - srid
      - subject
      - supplierArticle
      - techSize
      - totalPrice
      - warehouseName
      type: object
    get_incomes_200_response_inner:
      description: ""
      example:
        date: date
        supplierArticle: supplierArticle
        incomeId: 0
        quantity: 6
        totalPrice: 1.4658129805029452
        lastChangeDate: lastChangeDate
        nmId: 5
        warehouseName: warehouseName
        number: number
        dateClose: dateClose
        techSize: techSize
        barcode: barcode
        status: status
      properties:
        incomeId:
          description: Номер поставки
          format: int64
          type: integer
        number:
          description: Номер УПД
          type: string
        date:
          description: Дата поступления
          type: string
        lastChangeDate:
          description: Дата и время обновления данных в сервисе
          type: string
        supplierArticle:
          description: Артикул продавца
          type: string
        techSize:
          description: Размер
          type: string
        barcode:
          description: Штрих-код
          type: string
        quantity:
          description: Количество
          format: int32
          type: integer
        totalPrice:
          description: Цена из УПД
          type: number
        dateClose:
          description: Дата принятия (закрытия) у wildberies
          type: string
        warehouseName:
          description: Наименование склада
          type: string
        nmId:
          description: Код WB
          format: int64
          type: integer
        status:
          description: Текущий статус поставки
          type: string
      required:
      - barcode
      - date
      - dateClose
      - incomeId
      - lastChangeDate
      - nmId
      - number
      - quantity
      - status
      - supplierArticle
      - techSize
      - totalPrice
      - warehouseName
      type: object
    get_stocks_200_response_inner:
      example:
        daysOnSite: 5
        supplierArticle: supplierArticle
        isRealization: true
        quantity: 0
        Discount: 2.3021358869347655
        quantityFull: 6
        subject: subject
        lastChangeDate: 2000-01-23T04:56:07.000+00:00
        nmId: 1
        warehouseName: warehouseName
        SCCode: SCCode
        Price: 5.637376656633329
        isSupply: true
        techSize: techSize
        category: category
        barcode: barcode
        brand: brand
      properties:
        lastChangeDate:
          description: Дата и время обновления данных в сервисе
          format: date-time
          type: string
        supplierArticle:
          description: Артикул продавца
          type: string
        techSize:
          description: Размер
          type: string
        barcode:
          description: Штрих-код
          type: string
        quantity:
          description: Количество доступное для продажи
          format: int64
          type: integer
        isSupply:
          description: Договор поставки
          type: boolean
        isRealization:
          description: Договор реализации
          type: boolean
        quantityFull:
          description: Полное количество
          format: int64
          type: integer
        warehouseName:
          description: Название склада
          type: string
        nmId:
          description: Код wildberries
          format: int64
          type: integer
        subject:
          description: Предмет
          type: string
        category:
          description: Категория
          type: string
        daysOnSite:
          description: Количество дней на сайте
          format: int32
          type: integer
        brand:
          description: Бренд
          type: string
        SCCode:
          description: Код контракта
          type: string
        Price:
          description: Цена (?)
          type: number
        Discount:
          description: Скидка (?)
          type: number
      required:
      - Discount
      - Price
      - SCCode
      - barcode
      - brand
      - category
      - daysOnSite
      - isRealization
      - isSupply
      - lastChangeDate
      - nmId
      - quantity
      - quantityFull
      - subject
      - supplierArticle
      - techSize
      - warehouseName
      type: object
    get_sales_200_response_inner:
      example:
        date: date
        forPay: 3.616076749251911
        incomeID: 2
        odid: 7
        totalPrice: 6.027456183070403
        orderId: 5
        subject: subject
        regionName: regionName
        priceWithDisc: 4.145608029883936
        nmId: 7
        warehouseName: warehouseName
        gNumber: gNumber
        srid: srid
        number: number
        techSize: techSize
        barcode: barcode
        brand: brand
        promoCodeDiscount: 5.637376656633329
        supplierArticle: supplierArticle
        isRealization: true
        quantity: 0
        discountPercent: 1.4658129805029452
        saleID: saleID
        lastChangeDate: lastChangeDate
        spp: 9.301444243932576
        finishedPrice: 2.027123023002322
        oblastOkrugName: oblastOkrugName
        IsStorno: 1.2315135367772556
        isSupply: true
        countryName: countryName
        category: category
      properties:
        number:
          description: Номер документа
          type: string
        date:
          description: Дата продажи
          type: string
        lastChangeDate:
          description: Дата и время обновления информации в сервисе
          type: string
        supplierArticle:
          description: Артикул продавца
          type: string
        techSize:
          description: Размер
          type: string
        barcode:
          description: Штрих-код
          type: string
        quantity:
          description: Количество
          format: int64
          type: integer
        totalPrice:
          description: Начальная розничная цена товара
          type: number
        discountPercent:
          description: Согласованная скидка на товар
          type: number
        isSupply:
          description: Договор поставки
          type: boolean
        isRealization:
          description: Договор реализации
          type: boolean
        orderId:
          description: Идентификатор заказа
          format: int64
          type: integer
        promoCodeDiscount:
          description: Согласованный промокод
          type: number
        warehouseName:
          description: Склад отгрузки
          type: string
        countryName:
          description: Страна
          type: string
        oblastOkrugName:
          description: Округ
          type: string
        regionName:
          description: Регион
          type: string
        incomeID:
          description: Идентификатор поставки
          format: int64
          type: integer
        saleID:
          description: Уникальный идентификатор продажи/возврата
          type: string
        odid:
          description: Уникальный идентификатор позиции заказа
          format: int64
          type: integer
        spp:
          description: Согласованная скидка постоянного покупателя
          type: number
        forPay:
          description: К перечислению поставщику
          type: number
        finishedPrice:
          description: Фактическая цена из заказа с учетом всех скидок
          type: number
        priceWithDisc:
          description: "Цена, от которой считается вознаграждение поставщика forpay\
            \ (с учетом всех согласованных скидок)"
          type: number
        nmId:
          description: код wildberries
          format: int64
          type: integer
        subject:
          description: Предмет
          type: string
        category:
          description: Категория
          type: string
        brand:
          description: Бренд
          type: string
        IsStorno:
          description: (?)
          type: number
        gNumber:
          description: Номер заказа
          type: string
        srid:
          description: Srid
          type: string
      required:
      - IsStorno
      - barcode
      - brand
      - category
      - countryName
      - date
      - discountPercent
      - finishedPrice
      - forPay
      - gNumber
      - incomeID
      - isRealization
      - isSupply
      - lastChangeDate
      - nmId
      - number
      - oblastOkrugName
      - odid
      - orderId
      - priceWithDisc
      - promoCodeDiscount
      - quantity
      - regionName
      - saleID
      - spp
      - srid
      - subject
      - supplierArticle
      - techSize
      - totalPrice
      - warehouseName
      type: object
    get_paid_storage_200_response_inner:
      description: ""
      example:
        daysOnSite: 6
        nmId: 0
        techSize: techSize
        sumW: 5.637376656633329
        dayBeg: dayBeg
        dayEnd: dayEnd
        stock: 1
        saleQty: 5
      properties:
        dayBeg:
          description: Дата начала периода хранения
          type: string
        dayEnd:
          description: Дата завершения периода хранения
          type: string
        nmId:
          description: Код wildberries
          format: int64
          type: integer
        techSize:
          description: Размер
          type: string
        daysOnSite:
          description: Количество дней на сайте
          format: int32
          type: integer
        stock:
          description: Остаток на начало периода
          format: int64
          type: integer
        saleQty:
          description: Количество продано
          format: int64
          type: integer
        sumW:
          description: "Сумма за хранение, руб."
          type: number
      required:
      - dayBeg
      - dayEnd
      - daysOnSite
      - nmId
      - saleQty
      - stock
      - sumW
      - techSize
      type: object
    get_report_detail_by_period_200_response_inner:
      example:
        ppvz_sales_commission: 9.018348186070783
        retail_amount: 4.145608029883936
        rid: 9
        ppvz_vw: 6.965117697638846
        declaration_number: declaration_number
        retail_price: 2.027123023002322
        srid: srid
        ppvz_kvw_prc_base: 6.683562403749608
        rr_dt: rr_dt
        site_country: site_country
        sup_rating_prc_up: 0.8008281904610115
        create_dt: 2000-01-23T04:56:07.000+00:00
        product_discount_for_report: 4.965218492984954
        sale_dt: sale_dt
        barcode: barcode
        delivery_rub: 1.1730742509559433
        ppvz_supplier_inn: ppvz_supplier_inn
        ppvz_office_id: 0
        brand_name: brand_name
        date_to: 2000-01-23T04:56:07.000+00:00
        is_kgvp_v2: 6.027456183070403
        commission_percent: 1.2315135367772556
        order_dt: order_dt
        ts_name: ts_name
        ppvz_spp_prc: 9.369310271410669
        subject_name: subject_name
        sa_name: sa_name
        date_from: 2000-01-23T04:56:07.000+00:00
        return_amount: 7
        ppvz_reward: 3.5571952270680973
        gi_id: 0
        bonus_type_name: bonus_type_name
        sale_percent: 7.386281948385884
        penalty: 6.878052220127876
        ppvz_supplier_id: 0
        realizationreport_id: 5
        delivery_amount: 6
        gi_box_type_name: gi_box_type_name
        ppvz_kvw_prc: 8.762042012749001
        ppvz_for_pay: 6.438423552598547
        ppvz_vw_nds: 1.284659006116532
        acquiring_bank: acquiring_bank
        nm_id: 0
        supplier_oper_name: supplier_oper_name
        kiz: kiz
        ppvz_supplier_name: ppvz_supplier_name
        sticker_id: sticker_id
        quantity: 3
        suppliercontract_code: 5
        rrd_id: 0
        shk_id: 0
        supplier_promo: 5.025004791520295
        additional_payment: 5.944895607614016
        doc_type_name: doc_type_name
        office_name: office_name
        retail_price_withdisc_rub: 1.4894159098541704
        acquiring_fee: 1.4658129805029452
        ppvz_office_name: ppvz_office_name
      properties:
        date_from:
          description: Дата начала отчётного периода
          format: date-time
          type: string
        date_to:
          description: Дата конца отчётного периода
          format: date-time
          type: string
        create_dt:
          description: Дата формирования отчёта
          format: date-time
          type: string
          x-stoplight:
            id: c1y62zoqgz03q
        sup_rating_prc_up:
          description: "Размер снижения кВВ из-за рейтинга, %"
          type: number
        is_kgvp_v2:
          description: "Размер снижения кВВ из-за акции, %"
          type: number
        acquiring_fee:
          description: |-
            Возмещение расходов по эквайрингу.
            Расходы WB на услуги эквайринга: вычитаются из вознаграждения WB и не влияют на доход продавца
          type: number
        acquiring_bank:
          description: "Наименование банка, предоставляющего услуги эквайринг"
          type: string
        bonus_type_name:
          description: Обоснование штрафов и доплат
          type: string
        kiz:
          description: Код маркировки
          type: string
        realizationreport_id:
          description: Идентификатор отчёта
          type: integer
        suppliercontract_code:
          description: Договор
          type: integer
        rrd_id:
          description: Идентификатор записи
          exclusiveMinimum: false
          format: int64
          minimum: 0
          type: integer
        gi_id:
          description: Идентификатор поставки
          format: int64
          minimum: 0
          type: integer
        subject_name:
          description: Наименование товара
          minLength: 1
          type: string
        nm_id:
          description: SKU товара
          format: int64
          minimum: 0
          type: integer
        brand_name:
          description: Бренд товара
          minLength: 1
          type: string
        sa_name:
          description: Артикул поставщика
          minLength: 1
          type: string
        ts_name:
          description: Размер
          minLength: 1
          type: string
        barcode:
          description: Баркод
          minLength: 1
          type: string
        doc_type_name:
          description: Тип документа
          minLength: 1
          type: string
        quantity:
          description: Количество
          type: integer
        retail_price:
          description: Розничная цена
          type: number
        retail_amount:
          description: Сумма продаж (возвратов)
          type: number
        sale_percent:
          description: Согласованная скидка
          type: number
        commission_percent:
          description: Процент комиссии
          type: number
        office_name:
          description: Наименование склада
          minLength: 1
          type: string
        supplier_oper_name:
          description: Обоснование для оплаты (Тип операции?)
          minLength: 1
          type: string
        order_dt:
          description: Дата заказа
          minLength: 1
          type: string
        sale_dt:
          description: Дата продажи
          minLength: 1
          type: string
        rr_dt:
          description: Дата операции
          minLength: 1
          type: string
        shk_id:
          description: Штрих код (короба?)
          format: int64
          minimum: 0
          type: integer
        retail_price_withdisc_rub:
          description: Розничная цена с учётом согласованной скидки
          type: number
        delivery_amount:
          description: Количество доставок
          format: int32
          type: integer
        return_amount:
          description: Количество возвратов
          format: int32
          type: integer
        delivery_rub:
          description: Стоимость логистики
          type: number
        gi_box_type_name:
          description: Тип коробов
          minLength: 1
          type: string
        product_discount_for_report:
          description: Согласованный продуктовый дисконт
          type: number
        supplier_promo:
          description: Промокод
          type: number
        rid:
          description: Идентификатор заказа
          format: int64
          type: integer
        ppvz_spp_prc:
          description: Скидка постоянного покупателя
          type: number
        ppvz_kvw_prc_base:
          description: "Базовый размер коэффициента вознаграждения вайлдберриз без\
            \ НДС, %"
          type: number
        ppvz_kvw_prc:
          description: "Итоговый размер коэффициента вознаграждения вайлдберриз бе\
            з НДС, %"
          type: number
        ppvz_sales_commission:
          description: |-
            Вознаграждение с продаж до вычета услуг поверенного,
            без НДС
          type: number
        ppvz_for_pay:
          description: К перечислению продавцу за реализованный Товар
          type: number
        ppvz_reward:
          description: Возмещение расходов услуг поверенного
          type: number
        ppvz_vw:
          description: "Вознаграждение вайлдберриз, без НДС"
          type: number
        ppvz_vw_nds:
          description: НДС с вознаграждения вайлдберриз
          type: number
        ppvz_office_id:
          description: Идентификатор ПВЗ?
          format: int64
          minimum: 0
          type: integer
        ppvz_office_name:
          description: Наименование ПВЗ? (в случае если ppvz_office_id = 0)
          minLength: 1
          type: string
        ppvz_supplier_id:
          description: Идентификатор владельца ПВЗ?
          format: int64
          minimum: 0
          type: integer
        ppvz_supplier_name:
          description: Наименование владельца ПВЗ
          type: string
        ppvz_supplier_inn:
          description: ИНН владельца ПВЗ
          type: string
        declaration_number:
          description: Номер таможенной декларации
          type: string
        sticker_id:
          description: "Цифровое значение стикера, который клеится на товар в проц\
            ессе сборки заказа по системе Маркетплейс."
          type: string
        site_country:
          description: Страна продажи
          type: string
        penalty:
          description: Штрафы
          type: number
        additional_payment:
          description: Доплаты
          type: number
        srid:
          description: Новый идентификатор заказа
          type: string
      required:
      - additional_payment
      - barcode
      - brand_name
      - commission_percent
      - doc_type_name
      - gi_box_type_name
      - gi_id
      - office_name
      - penalty
      - ppvz_for_pay
      - ppvz_kvw_prc
      - ppvz_kvw_prc_base
      - ppvz_office_id
      - ppvz_reward
      - ppvz_sales_commission
      - ppvz_spp_prc
      - ppvz_supplier_id
      - ppvz_vw
      - ppvz_vw_nds
      - quantity
      - realizationreport_id
      - retail_amount
      - retail_price
      - rr_dt
      - rrd_id
      - sa_name
      - sale_percent
      - shk_id
      - subject_name
      - supplier_oper_name
      - ts_name
      type: object
  securitySchemes:
    Key:
      in: query
      name: key
      type: apiKey
